import { Theme } from '@src/types';
import { TButtonSizes, TButtonVariant } from '.';

export const getVariantStyle = (theme: Theme, variant: TButtonVariant) => {
  const variantStyles = {
    primaryBrand: {
      background: theme.SA600,
      pressedBackground: theme.SA900,
      text: theme.alphaWhite,
      pressedText: theme.alphaWhite,
      border: 'transparent',
      iconColor: theme.alphaWhite,
      disabledBackground: theme.gray200,
      disabledText: theme.gray400,
      disabledIcon: theme.gray400,
      borderDisabled: 'transparent',
    },
    primaryNeutral: {
      background: theme.gray950,
      pressedBackground: theme.gray600,
      text: theme.alphaWhite,
      pressedText: theme.alphaWhite,
      border: 'transparent',
      iconColor: theme.alphaWhite,
      disabledBackground: theme.gray200,
      disabledText: theme.gray400,
      disabledIcon: theme.gray400,
      borderDisabled: 'transparent',
    },
    secondarySolid: {
      background: theme.gray100,
      pressedBackground: theme.gray200,
      text: theme.gray1000,
      pressedText: theme.gray1000,
      border: 'transparent',
      iconColor: theme.gray1000,
      disabledBackground: theme.gray200,
      disabledText: theme.gray400,
      disabledIcon: theme.gray400,
      borderDisabled: 'transparent',
    },
    secondaryOutline: {
      background: 'transparent',
      pressedBackground: theme.gray200,
      text: theme.gray1000,
      pressedText: theme.gray1000,
      border: theme.gray300,
      iconColor: theme.gray1000,
      disabledBackground: 'transparent',
      disabledText: theme.gray400,
      disabledIcon: theme.gray400,
      borderDisabled: theme.gray400,
    },
    secondaryOutlineOnColor: {
      background: 'transparent',
      pressedBackground: 'rgba(255, 255, 255, 0.4)',
      text: theme.alphaWhite,
      pressedText: theme.alphaWhite,
      border: theme.gray300,
      iconColor: theme.alphaWhite,
      disabledIcon: theme.gray400,
      disabledBackground: 'transparent',
      disabledText: theme.gray400,
      borderDisabled: undefined,
    },
    transparent: {
      background: 'transparent',
      pressedBackground: 'transparent',
      text: theme.gray1000,
      pressedText: theme.SA900,
      border: 'transparent',
      iconColor: theme.gray1000,
      disabledBackground: 'transparent',
      disabledText: theme.gray400,
      disabledIcon: theme.gray400,
      borderDisabled: 'transparent',
    },
    subtle: {
      background: 'transparent',
      pressedBackground: theme.gray100,
      text: theme.gray1000,
      pressedText: theme.gray1000,
      border: 'transparent',
      iconColor: theme.gray1000,
      disabledBackground: 'transparent',
      disabledText: theme.gray400,
      disabledIcon: theme.gray400,
      borderDisabled: 'transparent',
    },
    destructivePrimary: {
      background: theme.error600,
      pressedBackground: theme.error900,
      text: theme.alphaWhite,
      pressedText: theme.alphaWhite,
      border: 'transparent',
      iconColor: theme.alphaWhite,
      disabledBackground: theme.gray200,
      disabledText: theme.gray400,
      disabledIcon: theme.gray400,
      borderDisabled: 'transparent',
    },
    destructiveSecondary: {
      background: theme.error50,
      pressedBackground: theme.error200,
      text: theme.error700,
      pressedText: theme.error700,
      border: 'transparent',
      iconColor: theme.error700,
      disabledBackground: theme.gray200,
      disabledText: theme.gray400,
      disabledIcon: theme.gray400,
      borderDisabled: 'transparent',
    },
    destructiveSecondaryOutline: {
      background: 'transparent',
      pressedBackground: theme.error200,
      text: theme.error700,
      pressedText: theme.error700,
      border: theme.error400,
      iconColor: theme.error700,
      disabledBackground: 'transparent',
      disabledText: theme.gray400,
      disabledIcon: theme.gray400,
      borderDisabled: theme.gray400,
    },
    destructiveSecondarySubtle: {
      background: 'transparent',
      pressedBackground: theme.error200,
      text: theme.error700,
      pressedText: theme.error700,
      border: 'transparent',
      iconColor: theme.error700,
      disabledBackground: 'transparent',
      disabledText: theme.gray400,
      disabledIcon: theme.gray400,
      borderDisabled: 'transparent',
    },
    destructiveTransparent: {
      background: 'transparent',
      pressedBackground: 'transparent',
      text: theme.error900,
      pressedText: theme.error900,
      border: 'transparent',
      iconColor: theme.error900,
      disabledBackground: 'transparent',
      disabledText: theme.gray400,
      disabledIcon: theme.gray400,
      borderDisabled: 'transparent',
    },

    whiteSolid: {
      background: theme.alphaWhite,
      pressedBackground: theme.gray15,
      text: theme.gray1000,
      pressedText: theme.gray1000,
      border: 'transparent',
      iconColor: theme.gray1000,
      disabledBackground: theme.gray10,
      disabledText: theme.gray20,
      disabledIcon: theme.gray20,
      borderDisabled: 'transparent',
    },
    whiteOutline: {
      background: 'transparent',
      pressedBackground: theme.gray20,
      text: theme.alphaWhite,
      pressedText: theme.alphaWhite,
      border: theme.gray20,
      iconColor: theme.alphaWhite,
      disabledBackground: 'transparent',
      disabledText: theme.gray20,
      disabledIcon: theme.gray20,
      borderDisabled: theme.gray20,
    },
    whiteSubtle: {
      background: 'transparent',
      pressedBackground: theme.SA300,
      text: theme.alphaWhite,
      pressedText: theme.alphaWhite,
      border: 'transparent',
      iconColor: theme.alphaWhite,
      disabledBackground: 'transparent',
      disabledText: theme.gray20,
      disabledIcon: theme.gray20,
      borderDisabled: 'transparent',
    },
    whiteTransparent: {
      background: theme.gray10,
      pressedBackground: theme.gray20,
      text: theme.alphaWhite,
      pressedText: theme.alphaWhite,
      border: 'transparent',
      iconColor: theme.alphaWhite,
      disabledBackground: 'transparent',
      disabledText: theme.gray20,
      disabledIcon: theme.gray20,
      borderDisabled: 'transparent',
    },
  };

  return variantStyles[variant];
};

export const getTextSize = (size: TButtonSizes) =>
  size === 'large' ? 'size_16' : size === 'medium' ? 'size_14' : 'size_12';

export const getLineHight = (size: TButtonSizes) =>
  size === 'large' ? 'hight_24' : size === 'medium' ? 'hight_20' : 'hight_18';
